// Generated by LispyScript v0.3.6
((typeof(window) === "undefined") ?
    console.log("Hello LispyScript!") :
    alert("Hello LispyScript!"));
console.log("hello");
console.log("hello LispyScript?");
((typeof(window) === "undefined") ?
    console.log("hello LispyScript") :
    alert("hello LispyScript"));
var square = function(x) {
    return (x * x);
};
Array.prototype.forEach.call([1, 2, 3],function(elem,index,list) {
    return console.log(elem);
});
